from __future__ import annotations

from copy import deepcopy
from typing import Any

BACKEND_PROFILE_SAMPLE: dict[str, Any] = {
    "featureProfiles": [
        {
            "featureCode": "SYLLABLE.COMPLEX_CODA",
            "accuracyRate": 0.42,
            "avgPronunciationScore": 54.0,
            "avgFixationDurationMs": 1350,
            "avgFixationCount": 3.1,
            "avgRegressionCount": 2.4,
            "skipRate": 0.18,
            "avgReadingTimeMs": 2800,
            "weaknessScore": 0.73,
            "confidence": 0.82,
            "evidenceCount": 15,
            "status": "WEAK",
            "analysisVersion": "WEAKNESS_V1",
            "analyzedAt": "2026-08-04T12:00:00",
        },
        {
            "featureCode": "PHONOLOGY.LIAISON",
            "accuracyRate": 0.64,
            "avgPronunciationScore": 68.0,
            "avgFixationDurationMs": 980,
            "avgFixationCount": 2.2,
            "avgRegressionCount": 1.3,
            "skipRate": 0.07,
            "avgReadingTimeMs": 2100,
            "weaknessScore": 0.51,
            "confidence": 0.76,
            "evidenceCount": 11,
            "status": "WATCH",
            "analysisVersion": "WEAKNESS_V1",
            "analyzedAt": "2026-08-04T12:00:00",
        },
    ],
    "featureLabels": {
        "SYLLABLE.COMPLEX_CODA": "겹받침 음절 읽기",
        "PHONOLOGY.LIAISON": "연음 읽기",
    },
    "gazeTrend": {
        "training": {
            "status": "NO_DATA",
            "comparisonAvailable": False,
            "points": [],
            "failedSessionCount": 0,
        },
        "test": {
            "status": "NO_DATA",
            "comparisonAvailable": False,
            "points": [],
            "failedSessionCount": 0,
        },
    },
    "recentTrainings": [
        {"trainingTemplateId": 22, "accuracy": 0.58, "daysAgo": 1},
    ],
}


def _profile(
    feature_code: str,
    *,
    accuracy: float,
    pronunciation: float,
    weakness: float,
    confidence: float,
    evidence_count: int,
    status: str,
    fixation_ms: int,
    fixation_count: float,
    regression_count: float,
    skip_rate: float,
    reading_time_ms: int,
) -> dict[str, Any]:
    return {
        "featureCode": feature_code,
        "accuracyRate": accuracy,
        "avgPronunciationScore": pronunciation,
        "avgFixationDurationMs": fixation_ms,
        "avgFixationCount": fixation_count,
        "avgRegressionCount": regression_count,
        "skipRate": skip_rate,
        "avgReadingTimeMs": reading_time_ms,
        "weaknessScore": weakness,
        "confidence": confidence,
        "evidenceCount": evidence_count,
        "status": status,
        "analysisVersion": "WEAKNESS_V1",
        "analyzedAt": "2026-08-04T12:00:00",
    }


LONG_BACKEND_PROFILE_SAMPLE: dict[str, Any] = {
    "featureProfiles": [
        _profile(
            "GRAPHEME.ONSET.BASIC.ㄱ",
            accuracy=0.94,
            pronunciation=94.0,
            weakness=0.08,
            confidence=0.92,
            evidence_count=24,
            status="NORMAL",
            fixation_ms=520,
            fixation_count=1.2,
            regression_count=0.2,
            skip_rate=0.01,
            reading_time_ms=920,
        ),
        _profile(
            "GRAPHEME.ONSET.BASIC.ㄴ",
            accuracy=0.91,
            pronunciation=92.0,
            weakness=0.10,
            confidence=0.91,
            evidence_count=22,
            status="NORMAL",
            fixation_ms=540,
            fixation_count=1.3,
            regression_count=0.2,
            skip_rate=0.01,
            reading_time_ms=970,
        ),
        _profile(
            "GRAPHEME.ONSET.TENSE.ㄲ",
            accuracy=0.84,
            pronunciation=86.0,
            weakness=0.25,
            confidence=0.84,
            evidence_count=14,
            status="NORMAL",
            fixation_ms=680,
            fixation_count=1.7,
            regression_count=0.5,
            skip_rate=0.02,
            reading_time_ms=1250,
        ),
        _profile(
            "GRAPHEME.VOWEL.BASIC.ㅏ",
            accuracy=0.95,
            pronunciation=96.0,
            weakness=0.06,
            confidence=0.94,
            evidence_count=25,
            status="NORMAL",
            fixation_ms=500,
            fixation_count=1.1,
            regression_count=0.1,
            skip_rate=0.0,
            reading_time_ms=880,
        ),
        _profile(
            "GRAPHEME.VOWEL.COMPOUND.ㅢ",
            accuracy=0.82,
            pronunciation=83.0,
            weakness=0.28,
            confidence=0.82,
            evidence_count=13,
            status="WATCH",
            fixation_ms=720,
            fixation_count=1.8,
            regression_count=0.6,
            skip_rate=0.03,
            reading_time_ms=1380,
        ),
        _profile(
            "GRAPHEME.CODA.SIMPLE.ㄱ",
            accuracy=0.88,
            pronunciation=89.0,
            weakness=0.20,
            confidence=0.88,
            evidence_count=18,
            status="NORMAL",
            fixation_ms=650,
            fixation_count=1.6,
            regression_count=0.4,
            skip_rate=0.02,
            reading_time_ms=1180,
        ),
        _profile(
            "GRAPHEME.CODA.COMPLEX.ㄺ",
            accuracy=0.81,
            pronunciation=80.0,
            weakness=0.31,
            confidence=0.81,
            evidence_count=12,
            status="WATCH",
            fixation_ms=790,
            fixation_count=2.0,
            regression_count=0.8,
            skip_rate=0.04,
            reading_time_ms=1520,
        ),
        _profile(
            "SYLLABLE.CV",
            accuracy=0.93,
            pronunciation=93.0,
            weakness=0.08,
            confidence=0.92,
            evidence_count=21,
            status="NORMAL",
            fixation_ms=560,
            fixation_count=1.3,
            regression_count=0.2,
            skip_rate=0.01,
            reading_time_ms=960,
        ),
        _profile(
            "SYLLABLE.CVC",
            accuracy=0.68,
            pronunciation=70.0,
            weakness=0.48,
            confidence=0.86,
            evidence_count=18,
            status="WATCH",
            fixation_ms=980,
            fixation_count=2.4,
            regression_count=1.3,
            skip_rate=0.08,
            reading_time_ms=2050,
        ),
        _profile(
            "SYLLABLE.COMPLEX_VOWEL",
            accuracy=0.76,
            pronunciation=77.0,
            weakness=0.41,
            confidence=0.80,
            evidence_count=12,
            status="WATCH",
            fixation_ms=900,
            fixation_count=2.1,
            regression_count=1.0,
            skip_rate=0.06,
            reading_time_ms=1870,
        ),
        _profile(
            "SYLLABLE.TENSE_ONSET",
            accuracy=0.83,
            pronunciation=84.0,
            weakness=0.29,
            confidence=0.79,
            evidence_count=11,
            status="WATCH",
            fixation_ms=800,
            fixation_count=1.9,
            regression_count=0.7,
            skip_rate=0.04,
            reading_time_ms=1590,
        ),
        _profile(
            "SYLLABLE.COMPLEX_CODA",
            accuracy=0.42,
            pronunciation=54.0,
            weakness=0.73,
            confidence=0.88,
            evidence_count=20,
            status="WEAK",
            fixation_ms=1350,
            fixation_count=3.1,
            regression_count=2.4,
            skip_rate=0.18,
            reading_time_ms=2800,
        ),
        _profile(
            "PHONOLOGY.LIAISON",
            accuracy=0.35,
            pronunciation=48.0,
            weakness=0.86,
            confidence=0.83,
            evidence_count=12,
            status="CRITICAL",
            fixation_ms=1480,
            fixation_count=3.4,
            regression_count=2.8,
            skip_rate=0.21,
            reading_time_ms=3150,
        ),
        _profile(
            "PHONOLOGY.NASALIZATION",
            accuracy=0.52,
            pronunciation=59.0,
            weakness=0.70,
            confidence=0.78,
            evidence_count=10,
            status="WEAK",
            fixation_ms=1260,
            fixation_count=2.9,
            regression_count=2.0,
            skip_rate=0.14,
            reading_time_ms=2670,
        ),
        _profile(
            "PHONOLOGY.PALATALIZATION",
            accuracy=0.61,
            pronunciation=66.0,
            weakness=0.55,
            confidence=0.72,
            evidence_count=8,
            status="WATCH",
            fixation_ms=1100,
            fixation_count=2.5,
            regression_count=1.6,
            skip_rate=0.10,
            reading_time_ms=2380,
        ),
        _profile(
            "WORD.SYLLABLE_COUNT.2",
            accuracy=0.74,
            pronunciation=73.0,
            weakness=0.43,
            confidence=0.76,
            evidence_count=11,
            status="WATCH",
            fixation_ms=1020,
            fixation_count=2.3,
            regression_count=1.2,
            skip_rate=0.08,
            reading_time_ms=2240,
        ),
        _profile(
            "WORD.PHONOLOGICALLY_CHANGED",
            accuracy=0.38,
            pronunciation=49.0,
            weakness=0.82,
            confidence=0.82,
            evidence_count=13,
            status="CRITICAL",
            fixation_ms=1510,
            fixation_count=3.5,
            regression_count=3.0,
            skip_rate=0.23,
            reading_time_ms=3300,
        ),
        _profile(
            "WORD.AUTOMATICITY",
            accuracy=0.32,
            pronunciation=52.0,
            weakness=0.88,
            confidence=0.84,
            evidence_count=14,
            status="CRITICAL",
            fixation_ms=1580,
            fixation_count=3.7,
            regression_count=3.2,
            skip_rate=0.25,
            reading_time_ms=3520,
        ),
        _profile(
            "SENTENCE.SIMPLE",
            accuracy=0.45,
            pronunciation=58.0,
            weakness=0.78,
            confidence=0.77,
            evidence_count=9,
            status="WEAK",
            fixation_ms=1420,
            fixation_count=3.2,
            regression_count=2.6,
            skip_rate=0.19,
            reading_time_ms=4100,
        ),
        _profile(
            "SENTENCE.PHRASE_BOUNDARY",
            accuracy=0.28,
            pronunciation=45.0,
            weakness=0.91,
            confidence=0.80,
            evidence_count=10,
            status="CRITICAL",
            fixation_ms=1660,
            fixation_count=3.9,
            regression_count=3.5,
            skip_rate=0.27,
            reading_time_ms=4680,
        ),
        _profile(
            "SENTENCE.FLUENCY",
            accuracy=0.22,
            pronunciation=43.0,
            weakness=0.94,
            confidence=0.82,
            evidence_count=10,
            status="CRITICAL",
            fixation_ms=1740,
            fixation_count=4.1,
            regression_count=3.8,
            skip_rate=0.30,
            reading_time_ms=4920,
        ),
    ],
    "featureLabels": {
        "GRAPHEME.ONSET.BASIC.ㄱ": "기본 초성 ㄱ 읽기",
        "GRAPHEME.ONSET.BASIC.ㄴ": "기본 초성 ㄴ 읽기",
        "GRAPHEME.ONSET.TENSE.ㄲ": "된소리 초성 ㄲ 읽기",
        "GRAPHEME.VOWEL.BASIC.ㅏ": "기본 모음 ㅏ 읽기",
        "GRAPHEME.VOWEL.COMPOUND.ㅢ": "복합 모음 ㅢ 읽기",
        "GRAPHEME.CODA.SIMPLE.ㄱ": "홑받침 ㄱ 읽기",
        "GRAPHEME.CODA.COMPLEX.ㄺ": "겹받침 ㄺ 읽기",
        "SYLLABLE.CV": "받침 없는 음절 읽기",
        "SYLLABLE.CVC": "받침 있는 음절 읽기",
        "SYLLABLE.COMPLEX_VOWEL": "복합 모음 음절 읽기",
        "SYLLABLE.TENSE_ONSET": "된소리 초성 음절 읽기",
        "SYLLABLE.COMPLEX_CODA": "겹받침 음절 읽기",
        "PHONOLOGY.LIAISON": "연음 읽기",
        "PHONOLOGY.NASALIZATION": "비음화 읽기",
        "PHONOLOGY.PALATALIZATION": "구개음화 읽기",
        "WORD.SYLLABLE_COUNT.2": "두 음절 단어 읽기",
        "WORD.PHONOLOGICALLY_CHANGED": "표기와 발음이 다른 단어 읽기",
        "WORD.AUTOMATICITY": "단어 읽기 자동성",
        "SENTENCE.SIMPLE": "단순 문장 읽기",
        "SENTENCE.PHRASE_BOUNDARY": "의미 단위 끊어 읽기",
        "SENTENCE.FLUENCY": "문장 읽기 유창성",
    },
    "gazeTrend": {
        "training": {
            "status": "AVAILABLE",
            "comparisonAvailable": True,
            "points": [
                {
                    "observedAt": "2026-07-21T10:00:00+09:00",
                    "totalVisitedDurationMs": 7600,
                    "totalVisitedCount": 28,
                    "reverseReadCount": 5,
                    "avgVisitedDurationMs": 910,
                },
                {
                    "observedAt": "2026-08-04T10:00:00+09:00",
                    "totalVisitedDurationMs": 6400,
                    "totalVisitedCount": 25,
                    "reverseReadCount": 3,
                    "avgVisitedDurationMs": 760,
                },
            ],
            "failedSessionCount": 0,
        },
        "test": {
            "status": "NO_DATA",
            "comparisonAvailable": False,
            "points": [],
            "failedSessionCount": 0,
        },
    },
    "recentTrainings": [
        {"trainingTemplateId": 17, "accuracy": 0.55, "daysAgo": 1},
        {"trainingTemplateId": 10, "accuracy": 0.83, "daysAgo": 3},
        {"trainingTemplateId": 15, "accuracy": 0.62, "daysAgo": 5},
        {"trainingTemplateId": 22, "accuracy": 0.38, "daysAgo": 8},
    ],
}


def backend_profile_sample() -> dict[str, Any]:
    return deepcopy(BACKEND_PROFILE_SAMPLE)


def long_backend_profile_sample() -> dict[str, Any]:
    return deepcopy(LONG_BACKEND_PROFILE_SAMPLE)


__all__ = [
    "BACKEND_PROFILE_SAMPLE",
    "LONG_BACKEND_PROFILE_SAMPLE",
    "backend_profile_sample",
    "long_backend_profile_sample",
]
